service_name: "movieService"

Postgres:
  host: localhost
  port: 6132
  user: postgres
  password: postgres
  DBName: online_movie_movies
  sslMode: allow

Server:
  host: 0.0.0.0
  port: "8000"      # gRPC
  httpPort: ":8081"   # HTTP для swagger.json

JWT:
  Secret: "your-very-secret-key"
  TTL: "30m"

Redis:
  host: redis
  port: 6379
  password: password
  db: 0

Secret: lio2UbeLoKlYuJ7LDR+kSxUPQDHbaekq
